from tikon.ecs.aprioris import APrioriDens

# A prioris for Opisina arenosella and associated parasitoids in coconut food web.
a_prioris = {
    'O. arenosella': [
        dict(etapa='huevo',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2, 4), 0.80),
             ),
        dict(etapa='huevo',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80),
             ),
        dict(etapa='huevo',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.1), 0.8)
             # apriori=APrioriDens((0.025, 0.029), 0.50),
             ),
        dict(etapa='huevo',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='juvenil_1',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens(((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * 1e-9 * .2,
                                  (1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * 1e-9 * .2), 0.80),
             ),
        dict(etapa='juvenil_1',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * .2 * 1e-9) ** 2,
                                  ((1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * .2 * 1e-9) ** 2), 0.80),
             ),
        dict(etapa='juvenil_1',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.05, 0.1), 0.8)  # por día
             ),
        dict(etapa='juvenil_1',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((5, 7), 0.80),
             ),
        dict(etapa='juvenil_1',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80),
             ),
        dict(etapa='juvenil_1',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='juvenil_2',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens(((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * 1e-9 * .2,
                                  (1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * 1e-9 * .2), 0.80),
             ),
        dict(etapa='juvenil_2',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * .2 * 1e-9) ** 2,
                                  ((1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * .2 * 1e-9) ** 2), 0.80)),
        dict(etapa='juvenil_2',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.00001, 0.001), 0.8),
             ),
        dict(etapa='juvenil_2',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((6, 8), 0.80),
             ),
        dict(etapa='juvenil_2',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil_2',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='juvenil_3',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens(((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * 1e-9 * .2,
                                  (1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * 1e-9 * .2), 0.80)),
        dict(etapa='juvenil_3',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * .2 * 1e-9) ** 2,
                                  ((1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * .2 * 1e-9) ** 2), 0.80)),
        dict(etapa='juvenil_3',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.00001, 0.005), 0.8)),
        dict(etapa='juvenil_3',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((5, 7), 0.80)),
        dict(etapa='juvenil_3',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil_3',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='juvenil_4',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens(((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * 1e-9 * .2,
                                  (1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * 1e-9 * .2), 0.80)),
        dict(etapa='juvenil_4',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * .2 * 1e-9) ** 2,
                                  ((1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * .2 * 1e-9) ** 2), 0.80)),
        dict(etapa='juvenil_4',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.001, 0.03), 0.8)),
        dict(etapa='juvenil_4',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((3, 5), 0.80)),
        dict(etapa='juvenil_4',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil_4',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='juvenil_5',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens(((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * 1e-9 * .2,
                                  (1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * 1e-9 * .2), 0.80)),
        dict(etapa='juvenil_5',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((((1823 - 100 * 1.96) / (53.1 + 10.64 * 1.96) * .2 * 1e-9) ** 2,
                                  ((1823 - 100 * 1.96) / (53.1 - 10.64 * 1.96) * .2 * 1e-9) ** 2), 0.80)),
        dict(etapa='juvenil_5',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.03, 0.04), 0.8)),
        dict(etapa='juvenil_5',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((5, 7), 0.80)),
        dict(etapa='juvenil_5',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil_5',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='pupa',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1)),
        dict(etapa='pupa',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 6), 0.80)),
        dict(etapa='pupa',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='pupa',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.001, 0.01), 0.8)),
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2.6, 8.4), 0.80)),
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 4), 0.80)),
        dict(etapa='adulto',
             categ='Reproducción', subcateg='Prob', ec='Normal', prm='n',
             apriori=APrioriDens((3, 5), 0.80)),
        dict(etapa='adulto',
             categ='Reproducción', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((2.5, 4.5), 0.80)),
        dict(etapa='adulto',
             categ='Reproducción', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='adulto',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.1), 1))
    ],

    'Parasitoide larvas': [
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((6, 7), 0.80)),
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             índs=['O. arenosella', 'O. arenosella juvenil_3'],
             apriori=APrioriDens((.005, .01), 0.80)),
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             índs=['O. arenosella', 'O. arenosella juvenil_4'],
             apriori=APrioriDens((.005, 0.01), 0.80)),
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             índs=['O. arenosella', 'O. arenosella juvenil_5'],
             apriori=APrioriDens((0.8, 1.0), 0.80)),
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((0, 2000), 0.80)),
        dict(etapa='adulto',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
        dict(etapa='pupa',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((9, 11), 0.80)),
        dict(etapa='pupa',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='pupa',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.0001, 0.001), 0.8)),
        dict(etapa='pupa',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Mult', ec='Linear', prm='a',
             apriori=APrioriDens((1.3, 2), 0.80)),
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((4, 5), 0.80)),
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0.0001, 0.01), 0.8)),
        dict(etapa='juvenil',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1))
    ],

    'Parasitoide pupa': [
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((32, 34), 0.80)),
        dict(etapa='adulto',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((2, 5), 0.80)),
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='a',
             apriori=APrioriDens((0.08, 0.1), 0.80)),  # ratio M:H = 2.8:1  (0.5 / 3.8, 1 / 3.8)
        dict(etapa='adulto',
             categ='Depredación', subcateg='Ecuación', ec='Kovai', prm='b',
             apriori=APrioriDens((0.8e5, 1.0e5), 0.80)),
        dict(etapa='adulto',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Mult', ec='Linear', prm='a',
             apriori=APrioriDens((4, 5), 0.80)),  #
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='mu',
             apriori=APrioriDens((7, 8), 0.80)),
        dict(etapa='juvenil',
             categ='Transiciones', subcateg='Prob', ec='Normal', prm='sigma',
             apriori=APrioriDens((1, 2), 0.80)),
        dict(etapa='juvenil',
             categ='Muertes', subcateg='Ecuación', ec='Constante', prm='q',
             apriori=APrioriDens((0, 0.01), 0.8)),
        dict(etapa='juvenil',
             categ='Estoc', subcateg='Dist', ec='Normal', prm='sigma',
             apriori=APrioriDens((0, 0.01), 1)),
    ]
}
